=== yurabh/learn_java_xml/input.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://nure.ua/your_last_name/practice7">
    <xs:element name="Users">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="User">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="Name"/>
                            <xs:element type="xs:integer" name="Age"/>
                            <xs:element name="City">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="LVIV"/>
                                        <xs:enumeration value="DNIPRO"/>
                                        <xs:enumeration value="KUIV"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element type="xs:string" name="Surname"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== yurabh/learn_java_xml/input.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<tns:Users xmlns:tns="http://nure.ua/your_last_name/practice7"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://nure.ua/your_last_name/practice7 input.xsd">
    <User>
        <Name>Oleg</Name>
        <Age>103</Age>
        <City>LVIV</City>
        <Surname>Popov</Surname>
    </User>

    <User>
        <Name>Andrew</Name>
        <Age>12</Age>
        <City>DNIPRO</City>
        <Surname>Work</Surname>
    </User>

    <User>
        <Name>Bred</Name>
        <Age>333</Age>
        <City>KUIV</City>
        <Surname>Pit</Surname>
    </User>

</tns:Users>
